---
{
   "kind": "pipeline",
   "name": "rspamd_multiarch",
   "platform": {
      "arch": [
         "linux/amd64",
         "linux/arm64"
      ],
      "os": "linux"
   },
   "steps": [
      {
         "image": "woodpeckerci/plugin-docker-buildx:2",
         "name": "pkg_multiarch",
         "privileged": true,
         "settings": {
            "build_args": [
               "RSPAMD_VERSION=${DRONE_SEMVER_SHORT}"
            ],
            "dockerfile": "Dockerfile.pkg",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": [
               "linux/amd64",
               "linux/arm64"
            ],
            "repo": "nerfd/rspamd",
            "tags": [
               "pkg-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "target": "pkg",
            "username": {
               "from_secret": "docker_username"
            }
         }
      },
      {
         "depends_on": [
            "pkg_amd64",
            "pkg_arm64"
         ],
         "image": "woodpeckerci/plugin-docker-buildx:2",
         "name": "install_multiarch",
         "privileged": true,
         "settings": {
            "build_args": [
               "LONG_VERSION=${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "dockerfile": "Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": [
               "linux/amd64",
               "linux/arm64"
            ],
            "repo": "nerfd/rspamd",
            "squash": true,
            "tags": [
               "image-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "target": "install",
            "username": {
               "from_secret": "docker_username"
            }
         }
      },
      {
         "depends_on": [
            "pkg_amd64",
            "pkg_arm64"
         ],
         "image": "woodpeckerci/plugin-docker-buildx:2",
         "name": "install_asan_multiarch",
         "privileged": true,
         "settings": {
            "build_args": [
               "LONG_VERSION=${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
               "ASAN_TAG=-asan"
            ],
            "dockerfile": "Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": [
               "linux/amd64",
               "linux/arm64"
            ],
            "repo": "nerfd/rspamd",
            "squash": true,
            "tags": [
               "image-asan-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "target": "install",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "tag"
         ]
      }
   },
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "prepromo_amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "apt-get update",
            "apt-get install -y git miltertest python3 python3-dev python3-pip python3-venv redis-server",
            "python3 -mvenv $DRONE_WORKSPACE/venv",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: setuptools==57.5.0\"",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: demjson psutil requests robotframework tornado\"",
            "git clone -b ${DRONE_SEMVER_SHORT} https://github.com/rspamd/rspamd.git",
            "RSPAMD_INSTALLROOT=/usr bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && umask 0000 && robot --removekeywords wuks --exclude isbroken $DRONE_WORKSPACE/rspamd/test/functional/cases\""
         ],
         "image": "nerfd/rspamd:image-amd64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
         "name": "pre_promotion_test",
         "user": "root"
      }
   ],
   "trigger": {
      "event": [
         "promote"
      ]
   },
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "prepromo_arm64",
   "platform": {
      "arch": "arm64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "apt-get update",
            "apt-get install -y git miltertest python3 python3-dev python3-pip python3-venv redis-server",
            "python3 -mvenv $DRONE_WORKSPACE/venv",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: setuptools==57.5.0\"",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: demjson psutil requests robotframework tornado\"",
            "git clone -b ${DRONE_SEMVER_SHORT} https://github.com/rspamd/rspamd.git",
            "RSPAMD_INSTALLROOT=/usr bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && umask 0000 && robot --removekeywords wuks --exclude isbroken $DRONE_WORKSPACE/rspamd/test/functional/cases\""
         ],
         "image": "nerfd/rspamd:image-arm64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
         "name": "pre_promotion_test",
         "user": "root"
      }
   ],
   "trigger": {
      "event": [
         "promote"
      ]
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "prepromo_amd64",
      "prepromo_arm64"
   ],
   "kind": "pipeline",
   "name": "promotion_multiarch",
   "steps": [
      {
         "image": "plugins/manifest",
         "name": "promote_multiarch",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "platforms": [
               "linux/amd64",
               "linux/arm64"
            ],
            "tags": [
               "latest",
               "${DRONE_SEMVER_MAJOR}.${DRONE_SEMVER_MINOR}"
            ],
            "target": "nerfd/rspamd:${DRONE_SEMVER_SHORT}",
            "template": "nerfd/rspamd:image-ARCH-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": [
         "promote"
      ]
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "prepromo_amd64",
      "prepromo_arm64"
   ],
   "kind": "pipeline",
   "name": "promotion_multiarch_asan",
   "steps": [
      {
         "image": "plugins/manifest",
         "name": "promote_multiarch_asan",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "platforms": [
               "linux/amd64",
               "linux/arm64"
            ],
            "tags": [
               "asan-latest",
               "asan-${DRONE_SEMVER_MAJOR}.${DRONE_SEMVER_MINOR}"
            ],
            "target": "nerfd/rspamd:asan-${DRONE_SEMVER_SHORT}",
            "template": "nerfd/rspamd:image-asan-ARCH-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": [
         "promote"
      ]
   },
   "type": "docker"
}
---
{
   "hmac": "0000000000000000000000000000000000000000000000000000000000000000",
   "kind": "signature"
}
...
