---
{
   "kind": "pipeline",
   "name": "cron_preflight",
   "steps": [
      {
         "commands": [
            "dpkg-query -W -f='$${Version}' rspamd > /state/DOCKER_VERSION"
         ],
         "image": "nerfd/rspamd:nightly",
         "name": "get_nightly_version",
         "pull": "always",
         "user": "root",
         "volumes": [
            {
               "name": "state",
               "path": "/state"
            }
         ]
      },
      {
         "commands": [
            "bash -c 'export GIT_VERSION=`git ls-remote -q https://github.com/rspamd/rspamd.git refs/heads/master` && export GIT_VERSION=$$((16#$${GIT_VERSION:0:9})) && export DOCKER_VERSION=`cat /state/DOCKER_VERSION` && if [ \"$$GIT_VERSION\" = \"$$DOCKER_VERSION\" ]; then echo no update needed; else echo $${DOCKER_VERSION} != $${GIT_VERSION}; fi'"
         ],
         "image": "bitnami/git",
         "name": "compare_git_version",
         "volumes": [
            {
               "name": "state",
               "path": "/state"
            }
         ]
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "cron"
         ]
      }
   },
   "type": "docker",
   "volumes": [
      {
         "name": "state",
         "temp": { }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "rspamd_amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "image": "rspamd/drone-docker-plugin",
         "name": "install_amd64",
         "privileged": true,
         "settings": {
            "build_args": [
               "PKG_TAG=pkg-amd64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
               "TARGETARCH=amd64"
            ],
            "dockerfile": "Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": "linux/amd64",
            "repo": "nerfd/rspamd",
            "squash": true,
            "tags": [
               "image-amd64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "target": "install",
            "username": {
               "from_secret": "docker_username"
            }
         }
      },
      {
         "image": "rspamd/drone-docker-plugin",
         "name": "install_asan_amd64",
         "privileged": true,
         "settings": {
            "build_args": [
               "PKG_TAG=pkg-amd64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
               "TARGETARCH=amd64",
               "ASAN_TAG=-asan"
            ],
            "dockerfile": "Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": "linux/amd64",
            "repo": "nerfd/rspamd",
            "squash": true,
            "tags": [
               "image-asan-amd64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "target": "install",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "tag"
         ]
      }
   },
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "rspamd_arm64",
   "platform": {
      "arch": "arm64",
      "os": "linux"
   },
   "steps": [
      {
         "image": "rspamd/drone-docker-plugin",
         "name": "install_arm64",
         "privileged": true,
         "settings": {
            "build_args": [
               "PKG_TAG=pkg-arm64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
               "TARGETARCH=arm64"
            ],
            "dockerfile": "Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": "linux/arm64",
            "repo": "nerfd/rspamd",
            "squash": true,
            "tags": [
               "image-arm64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "target": "install",
            "username": {
               "from_secret": "docker_username"
            }
         }
      },
      {
         "image": "rspamd/drone-docker-plugin",
         "name": "install_asan_arm64",
         "privileged": true,
         "settings": {
            "build_args": [
               "PKG_TAG=pkg-arm64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
               "TARGETARCH=arm64",
               "ASAN_TAG=-asan"
            ],
            "dockerfile": "Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": "linux/arm64",
            "repo": "nerfd/rspamd",
            "squash": true,
            "tags": [
               "image-asan-arm64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}"
            ],
            "target": "install",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "tag"
         ]
      }
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "cron_preflight"
   ],
   "kind": "pipeline",
   "name": "cron_rspamd_amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "image": "rspamd/drone-docker-plugin",
         "name": "install_amd64",
         "privileged": true,
         "settings": {
            "build_args": [
               "PKG_TAG=pkg-amd64-nightly",
               "TARGETARCH=amd64"
            ],
            "dockerfile": "Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": "linux/amd64",
            "repo": "nerfd/rspamd",
            "squash": true,
            "tags": [
               "nightly-amd64"
            ],
            "target": "install",
            "username": {
               "from_secret": "docker_username"
            }
         }
      },
      {
         "image": "rspamd/drone-docker-plugin",
         "name": "install_asan_amd64",
         "privileged": true,
         "settings": {
            "build_args": [
               "PKG_TAG=pkg-amd64-nightly",
               "TARGETARCH=amd64",
               "ASAN_TAG=-asan"
            ],
            "dockerfile": "Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": "linux/amd64",
            "repo": "nerfd/rspamd",
            "squash": true,
            "tags": [
               "nightly-asan-amd64"
            ],
            "target": "install",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "cron"
         ]
      }
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "cron_preflight"
   ],
   "kind": "pipeline",
   "name": "cron_rspamd_arm64",
   "platform": {
      "arch": "arm64",
      "os": "linux"
   },
   "steps": [
      {
         "image": "rspamd/drone-docker-plugin",
         "name": "install_arm64",
         "privileged": true,
         "settings": {
            "build_args": [
               "PKG_TAG=pkg-arm64-nightly",
               "TARGETARCH=arm64"
            ],
            "dockerfile": "Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": "linux/arm64",
            "repo": "nerfd/rspamd",
            "squash": true,
            "tags": [
               "nightly-arm64"
            ],
            "target": "install",
            "username": {
               "from_secret": "docker_username"
            }
         }
      },
      {
         "image": "rspamd/drone-docker-plugin",
         "name": "install_asan_arm64",
         "privileged": true,
         "settings": {
            "build_args": [
               "PKG_TAG=pkg-arm64-nightly",
               "TARGETARCH=arm64",
               "ASAN_TAG=-asan"
            ],
            "dockerfile": "Dockerfile",
            "password": {
               "from_secret": "docker_password"
            },
            "platform": "linux/arm64",
            "repo": "nerfd/rspamd",
            "squash": true,
            "tags": [
               "nightly-asan-arm64"
            ],
            "target": "install",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "cron"
         ]
      }
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "rspamd_amd64",
      "rspamd_arm64"
   ],
   "kind": "pipeline",
   "name": "rspamd_multiarch",
   "steps": [
      {
         "image": "plugins/manifest",
         "name": "multiarch_image",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "platforms": [
               "linux/amd64",
               "linux/arm64"
            ],
            "target": "nerfd/rspamd:image-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
            "template": "nerfd/rspamd:image-ARCH-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
            "username": {
               "from_secret": "docker_username"
            }
         }
      },
      {
         "image": "plugins/manifest",
         "name": "multiarch_asan_image",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "platforms": [
               "linux/amd64",
               "linux/arm64"
            ],
            "target": "nerfd/rspamd:image-asan-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
            "template": "nerfd/rspamd:image-asan-ARCH-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "tag"
         ]
      }
   },
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "prepromo_amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "apt-get update",
            "apt-get install -y git miltertest python3 python3-dev python3-pip python3-venv redis-server",
            "python3 -mvenv $DRONE_WORKSPACE/venv",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: setuptools==57.5.0\"",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: demjson psutil requests robotframework tornado\"",
            "git clone -b ${DRONE_SEMVER_SHORT} https://github.com/rspamd/rspamd.git",
            "RSPAMD_INSTALLROOT=/usr bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && umask 0000 && robot --removekeywords wuks --exclude isbroken $DRONE_WORKSPACE/rspamd/test/functional/cases\""
         ],
         "image": "nerfd/rspamd:image-amd64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
         "name": "pre_promotion_test",
         "user": "root"
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "promote"
         ]
      }
   },
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "prepromo_arm64",
   "platform": {
      "arch": "arm64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "apt-get update",
            "apt-get install -y git miltertest python3 python3-dev python3-pip python3-venv redis-server",
            "python3 -mvenv $DRONE_WORKSPACE/venv",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: setuptools==57.5.0\"",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: demjson psutil requests robotframework tornado\"",
            "git clone -b ${DRONE_SEMVER_SHORT} https://github.com/rspamd/rspamd.git",
            "RSPAMD_INSTALLROOT=/usr bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && umask 0000 && robot --removekeywords wuks --exclude isbroken $DRONE_WORKSPACE/rspamd/test/functional/cases\""
         ],
         "image": "nerfd/rspamd:image-arm64-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
         "name": "pre_promotion_test",
         "user": "root"
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "promote"
         ]
      }
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "cron_rspamd_amd64"
   ],
   "kind": "pipeline",
   "name": "cron_prepromo_amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "apt-get update",
            "apt-get install -y git miltertest python3 python3-dev python3-pip python3-venv redis-server",
            "python3 -mvenv $DRONE_WORKSPACE/venv",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: setuptools==57.5.0\"",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: demjson psutil requests robotframework tornado\"",
            "git clone -b master https://github.com/rspamd/rspamd.git",
            "RSPAMD_INSTALLROOT=/usr bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && umask 0000 && robot --removekeywords wuks --exclude isbroken $DRONE_WORKSPACE/rspamd/test/functional/cases\""
         ],
         "image": "nerfd/rspamd:nightly-amd64",
         "name": "pre_promotion_test",
         "user": "root"
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "cron"
         ]
      }
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "cron_rspamd_arm64"
   ],
   "kind": "pipeline",
   "name": "cron_prepromo_arm64",
   "platform": {
      "arch": "arm64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "apt-get update",
            "apt-get install -y git miltertest python3 python3-dev python3-pip python3-venv redis-server",
            "python3 -mvenv $DRONE_WORKSPACE/venv",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: setuptools==57.5.0\"",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: demjson psutil requests robotframework tornado\"",
            "git clone -b master https://github.com/rspamd/rspamd.git",
            "RSPAMD_INSTALLROOT=/usr bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && umask 0000 && robot --removekeywords wuks --exclude isbroken $DRONE_WORKSPACE/rspamd/test/functional/cases\""
         ],
         "image": "nerfd/rspamd:nightly-arm64",
         "name": "pre_promotion_test",
         "user": "root"
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "cron"
         ]
      }
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "prepromo_amd64",
      "prepromo_arm64"
   ],
   "kind": "pipeline",
   "name": "promotion_multiarch",
   "steps": [
      {
         "image": "plugins/manifest",
         "name": "promote_multiarch",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "platforms": [
               "linux/amd64",
               "linux/arm64"
            ],
            "tags": [
               "latest",
               "${DRONE_SEMVER_MAJOR}.${DRONE_SEMVER_MINOR}"
            ],
            "target": "nerfd/rspamd:${DRONE_SEMVER_SHORT}",
            "template": "nerfd/rspamd:image-ARCH-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "promote"
         ]
      }
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "prepromo_amd64",
      "prepromo_arm64"
   ],
   "kind": "pipeline",
   "name": "promotion_multiarch_asan",
   "steps": [
      {
         "image": "plugins/manifest",
         "name": "promote_multiarch_asan",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "platforms": [
               "linux/amd64",
               "linux/arm64"
            ],
            "tags": [
               "asan-latest",
               "asan-${DRONE_SEMVER_MAJOR}.${DRONE_SEMVER_MINOR}"
            ],
            "target": "nerfd/rspamd:asan-${DRONE_SEMVER_SHORT}",
            "template": "nerfd/rspamd:image-asan-ARCH-${DRONE_SEMVER_SHORT}-${DRONE_SEMVER_BUILD}",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "promote"
         ]
      }
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "cron_prepromo_amd64",
      "cron_prepromo_arm64"
   ],
   "kind": "pipeline",
   "name": "cron-promotion",
   "steps": [
      {
         "image": "plugins/manifest",
         "name": "cron_promotion",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "platforms": [
               "linux/amd64",
               "linux/arm64"
            ],
            "target": "nerfd/rspamd:nightly",
            "template": "nerfd/rspamd:nightly-ARCH",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "cron"
         ]
      }
   },
   "type": "docker"
}
---
{
   "depends_on": [
      "cron_prepromo_amd64",
      "cron_prepromo_arm64"
   ],
   "kind": "pipeline",
   "name": "cron-asan-promotion",
   "steps": [
      {
         "image": "plugins/manifest",
         "name": "cron_promotion",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "platforms": [
               "linux/amd64",
               "linux/arm64"
            ],
            "target": "nerfd/rspamd:asan-nightly",
            "template": "nerfd/rspamd:nightly-asan-ARCH",
            "username": {
               "from_secret": "docker_username"
            }
         }
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "cron"
         ]
      }
   },
   "type": "docker"
}
---
{
   "hmac": "0000000000000000000000000000000000000000000000000000000000000000",
   "kind": "signature"
}
...
