---
{
   "depends_on": [ ],
   "kind": "pipeline",
   "name": "cron_prepromo_amd64",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "apt-get update",
            "apt-get install -y git miltertest python3 python3-dev python3-pip python3-venv redis-server",
            "python3 -mvenv $DRONE_WORKSPACE/venv",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: setuptools==57.5.0\"",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: demjson psutil requests robotframework tornado\"",
            "git clone -b master https://github.com/rspamd/rspamd.git",
            "RSPAMD_INSTALLROOT=/usr bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && umask 0000 && robot --removekeywords wuks --exclude isbroken $DRONE_WORKSPACE/rspamd/test/functional/cases\""
         ],
         "image": "rspamd/rspamd:nightly-amd64",
         "name": "pre_promotion_test",
         "user": "root"
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "cron"
         ]
      }
   },
   "type": "docker"
}
---
{
   "depends_on": [ ],
   "kind": "pipeline",
   "name": "cron_prepromo_arm64",
   "platform": {
      "arch": "arm64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "apt-get update",
            "apt-get install -y git miltertest python3 python3-dev python3-pip python3-venv redis-server",
            "python3 -mvenv $DRONE_WORKSPACE/venv",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: setuptools==57.5.0\"",
            "bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: demjson psutil requests robotframework tornado\"",
            "git clone -b master https://github.com/rspamd/rspamd.git",
            "RSPAMD_INSTALLROOT=/usr bash -c \"source $DRONE_WORKSPACE/venv/bin/activate && umask 0000 && robot --removekeywords wuks --exclude isbroken $DRONE_WORKSPACE/rspamd/test/functional/cases\""
         ],
         "image": "rspamd/rspamd:nightly-arm64",
         "name": "pre_promotion_test",
         "user": "root"
      }
   ],
   "trigger": {
      "event": {
         "include": [
            "cron"
         ]
      }
   },
   "type": "docker"
}
---
{
   "hmac": "0000000000000000000000000000000000000000000000000000000000000000",
   "kind": "signature"
}
...
