name: build_test_promote

on:
  workflow_call:
    inputs:
      dockerhub_name:
        default: rspamd/rspamd
        required: false
        type: string
      nightly:
        default: true
        required: false
        type: boolean

jobs:
  build_amd64:
    uses: ./.github/workflows/docker_build.yml
    with:
      nightly: ${{ inputs.nightly }}
      dockerhub_name: ${{ inputs.dockerhub_name }}
      platform: amd64
    permissions:
      packages: write
      contents: read
    secrets: inherit

  build_arm64:
    uses: ./.github/workflows/docker_build.yml
    with:
      nightly: ${{ inputs.nightly }}
      dockerhub_name: ${{ inputs.dockerhub_name }}
      platform: arm64
    permissions:
      packages: write
      contents: read
    secrets: inherit

  test_amd64:
    needs: [build_amd64]
    uses: ./.github/workflows/rspamd_test.yml
    with:
      image: ghcr.io/${{ github.repository }}@${{ needs.build_amd64.outputs.digest_release }}
      tag: "${{ needs.build_amd64.outputs.tag }}"

  test_arm64:
    needs: [build_arm64]
    uses: ./.github/workflows/rspamd_test.yml
    with:
      image: ghcr.io/${{ github.repository }}@${{ needs.build_arm64.outputs.digest_release }}
      tag: "${{ needs.build_arm64.outputs.tag }}"

  promote:
    needs: [test_amd64, test_arm64]
    uses: ./.github/workflows/promote.yml
    with:
      images: ghcr.io/${{ github.repository }}@${{ needs.build_amd64.outputs.digest_release }},ghcr.io/${{ github.repository }}@${{ needs.build_arm64.outputs.digest_release }}
      images_asan: ghcr.io/${{ github.repository }}@${{ needs.build_amd64.outputs.digest_asan }},ghcr.io/${{ github.repository }}@${{ needs.build_arm64.outputs.digest_asan }}
      dockerhub_tags_asan: "${{ needs.build.outputs.dockerhub_tags_asan }}"
      dockerhub_tags_release: "${{ needs.build.outputs.dockerhub_tags_release }}"
      ghcr_tags_asan: "${{ needs.build.outputs.ghcr_tags_asan }}"
      ghcr_tags_release: "${{ needs.build.outputs.ghcr_tags_release }}"
    secrets: inherit
