name: Publish Docker image

on:
  workflow_call:
    inputs:
      nightly:
        default: true
        required: false
        type: boolean

jobs:
  docker_build:
    name: docker_build
    runs-on: ["ubuntu-latest"]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        run: |
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Set nightly-specific variables
        if: ${{ inputs.nightly }}
        run: |
          echo "PKG_TAG_SUFFIX=-nightly" >> "$GITHUB_ENV"
          echo "RSPAMD_GIT=master" >> "$GITHUB_ENV"
          echo "RSPAMD_VERSION=auto" >> "$GITHUB_ENV"

      - name: Set release-specific variables
        if: ${{ ! inputs.nightly }}
        run: |
          echo "PKG_TAG_SUFFIX=" >> "$GITHUB_ENV"
          echo "RSPAMD_GIT=`echo ${{ github.ref_name }} | sed s/^v// | sed s/+.//`" >> "$GITHUB_ENV"
          echo "RSPAMD_VERSION=`echo ${{ github.ref_name }} | sed s/^v// | sed s/+.//`" >> "$GITHUB_ENV"

      - name: Build pkg image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            RSPAMD_GIT=${{ env.RSPAMD_GIT }}
            RSPAMD_VERSION={{ env.RSPAMD_VERSION }}
          file: Dockerfile.pkg
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:pkg${{ env.PKG_TAG_SUFFIX }}
