name: lametest

on:
  workflow_dispatch:

jobs:
  bump:
    runs-on: "ubuntu-22.04"
    permissions:
      actions: write
      contents: write
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump tag for no particular reason
        uses: ./.github/actions/bump_tag
