name: nightly

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build_test_promote:
    uses: ./.github/workflows/build_test_promote.yml
    with:
      nightly: true
    permissions:
      packages: write
      contents: read
    secrets: inherit
