name: rspamd_test

on:
  workflow_call:
    inputs:
      dockerhub_tags_asan:
        required: true
        type: string
      dockerhub_tags_release:
        required: true
        type: string
      image:
        required: true
        type: string
      image_asan:
        required: true
        type: string

jobs:
  promote:
    runs-on: "ubuntu-latest"
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Log in to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sign images
        run: |
          cosign sign ${{ inputs.image }}

      - name: Push image
        run: |
          IFS=, read -a tags <<< "${{ inputs.dockerhub_tags_release }}"
          for i in ${tags[@]}
          do
            docker image tag ${{ inputs.image }} ${tag}
            docker push ${tag}
          done

      - name: Push ASAN image
        run: |
          IFS=, read -a tags <<< "${{ inputs.dockerhub_tags_asan }}"
          for i in ${tags[@]}
          do
            docker image tag ${{ inputs.image_asan }} ${tag}
            docker push ${tag}
          done
