name: promote

on:
  workflow_call:
    inputs:
      dockerhub_tags_asan:
        required: true
        type: string
      dockerhub_tags_release:
        required: true
        type: string
      ghcr_tags_asan:
        required: true
        type: string
      ghcr_tags_release:
        required: true
        type: string
      images:
        required: true
        type: string
      images_asan:
        required: true
        type: string

jobs:
  promote:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Log in to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image (dockerhub)
        run: |
          IFS=, read -a tags <<< "${{ inputs.dockerhub_tags_release }}"
          for tag in ${tags[@]}
          do
            TAGLIST+=" -t ${tag} "
          done
          docker buildx imagetools create ${TAGLIST} ${{ inputs.images }}

      - name: Push ASAN image (dockerhub)
        run: |
          IFS=, read -a tags <<< "${{ inputs.dockerhub_tags_asan }}"
          for tag in ${tags[@]}
          do
            TAGLIST+=" -t ${tag} "
          done
          docker buildx imagetools create ${TAGLIST} ${{ inputs.images_asan }}

      - name: Push image (ghcr)
        run: |
          IFS=, read -a tags <<< "${{ inputs.ghcr_tags_release }}"
          for tag in ${tags[@]}
          do
            TAGLIST+=" -t ${tag} "
          done
          docker buildx imagetools create ${TAGLIST} ${{ inputs.images }}

      - name: Push ASAN image (ghcr)
        run: |
          IFS=, read -a tags <<< "${{ inputs.ghcr_tags_asan }}"
          for tag in ${tags[@]}
          do
            TAGLIST+=" -t ${tag} "
          done
          docker buildx imagetools create ${TAGLIST} ${{ inputs.images_asan }}
