name: promote

on:
  workflow_call:
    inputs:
      dockerhub_tags_asan:
        required: true
        type: string
      dockerhub_tags_release:
        required: true
        type: string
      ghcr_tags_asan:
        required: true
        type: string
      ghcr_tags_release:
        required: true
        type: string
      images:
        required: true
        type: string
      images_asan:
        required: true
        type: string

jobs:
  promote:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push release image to GHCR
        run: |
          IFS=, read -a tags <<< "${{ inputs.ghcr_tags_release }}"
          IMAGES="${{ inputs.images }}"
          IMAGES="${IMAGES//,/ }"
          for tag in ${tags[@]}
          do
            TAGLIST+=" -t ${tag} "
          done
          docker buildx imagetools create ${TAGLIST} ${IMAGES}

      - name: Push ASAN image to GHCR
        run: |
          IFS=, read -a tags <<< "${{ inputs.ghcr_tags_asan }}"
          IMAGES="${{ inputs.images_asan }}"
          IMAGES="${IMAGES//,/ }"
          for tag in ${tags[@]}
          do
            TAGLIST+=" -t ${tag} "
          done
          docker buildx imagetools create ${TAGLIST} ${IMAGES}

      - name: Check for Dockerhub secrets
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ]; then
            echo "HAVE_DOCKERHUB=1" >> $GITHUB_ENV
          else
            echo "HAVE_DOCKERHUB=0" >> $GITHUB_ENV
          fi

      - name: Log in to Dockerhub
        if: ${{ env.HAVE_DOCKERHUB }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push release image to Dockerhub
        if: ${{ env.HAVE_DOCKERHUB }}
        run: |
          IFS=, read -a tags <<< "${{ inputs.dockerhub_tags_release }}"
          IMAGES="${{ inputs.images }}"
          IMAGES="${IMAGES//,/ }"
          for tag in ${tags[@]}
          do
            TAGLIST+=" -t ${tag} "
          done
          docker buildx imagetools create ${TAGLIST} ${IMAGES}

      - name: Push ASAN image to Dockerhub
        if: ${{ env.HAVE_DOCKERHUB }}
        run: |
          IFS=, read -a tags <<< "${{ inputs.dockerhub_tags_asan }}"
          IMAGES="${{ inputs.images_asan }}"
          IMAGES="${IMAGES//,/ }"
          for tag in ${tags[@]}
          do
            TAGLIST+=" -t ${tag} "
          done
          docker buildx imagetools create ${TAGLIST} ${IMAGES}
