name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+\\+[0-9]+"

jobs:
  release:
    uses: ./.github/workflows/docker_build.yml
    with:
      nightly: false
    permissions:
      packages: write
      contents: read
    secrets: inherit

  test:
    needs: [docker_build]
    uses: ./.github/workflows/rspamd_test.yml
    with:
      image: ghcr.io/${{ github.repository }}:latest
      # FIXME: use RSPAMD_GIT as output
      tag: 3.8.4
