name: rspamd_test

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  rspamd_test:
    runs-on: "ubuntu-latest"
    container:
      image: ${{ inputs.image }}
      options: --user root
    steps:
      - name: Run tests
        run: |
          apt-get update
          apt-get install -y git miltertest python3 python3-dev python3-pip python3-venv redis-server
          mkdir -p $GITHUB_WORKSPACE
          python3 -mvenv $GITHUB_WORKSPACE/venv
          bash -c "source $GITHUB_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: setuptools==57.5.0"
          bash -c "source $GITHUB_WORKSPACE/venv/bin/activate && pip3 install --no-cache --disable-pip-version-check --no-binary :all: demjson psutil requests robotframework tornado"
          git clone -b ${{ inputs.tag }} https://github.com/rspamd/rspamd.git
          RSPAMD_INSTALLROOT=/usr bash -c "source $GITHUB_WORKSPACE/venv/bin/activate && robot --removekeywords wuks --exclude isbroken $GITHUB_WORKSPACE/rspamd/test/functional/cases"
